// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDirectory(arg1, arg2) {
  return window['go']['main']['App']['AddDirectory'](arg1, arg2);
}

export function AddTagToVideo(arg1, arg2) {
  return window['go']['main']['App']['AddTagToVideo'](arg1, arg2);
}

export function AddVideo(arg1) {
  return window['go']['main']['App']['AddVideo'](arg1);
}

export function AnalyzeVideoFaces(arg1) {
  return window['go']['main']['App']['AnalyzeVideoFaces'](arg1);
}

export function ApproveAITagCandidate(arg1) {
  return window['go']['main']['App']['ApproveAITagCandidate'](arg1);
}

export function BatchAddTagToVideos(arg1, arg2) {
  return window['go']['main']['App']['BatchAddTagToVideos'](arg1, arg2);
}

export function BatchDeleteVideos(arg1, arg2) {
  return window['go']['main']['App']['BatchDeleteVideos'](arg1, arg2);
}

export function BatchRefreshVideoMetadata(arg1) {
  return window['go']['main']['App']['BatchRefreshVideoMetadata'](arg1);
}

export function BatchRemoveTagFromVideos(arg1, arg2) {
  return window['go']['main']['App']['BatchRemoveTagFromVideos'](arg1, arg2);
}

export function CancelSubtitle() {
  return window['go']['main']['App']['CancelSubtitle']();
}

export function CheckSubtitleDependencies() {
  return window['go']['main']['App']['CheckSubtitleDependencies']();
}

export function CreateTag(arg1, arg2) {
  return window['go']['main']['App']['CreateTag'](arg1, arg2);
}

export function DeleteDirectory(arg1) {
  return window['go']['main']['App']['DeleteDirectory'](arg1);
}

export function DeleteTag(arg1) {
  return window['go']['main']['App']['DeleteTag'](arg1);
}

export function DeleteVideo(arg1, arg2) {
  return window['go']['main']['App']['DeleteVideo'](arg1, arg2);
}

export function DownloadSubtitleDependencies() {
  return window['go']['main']['App']['DownloadSubtitleDependencies']();
}

export function ForceGenerateSubtitle(arg1) {
  return window['go']['main']['App']['ForceGenerateSubtitle'](arg1);
}

export function GenerateSubtitle(arg1) {
  return window['go']['main']['App']['GenerateSubtitle'](arg1);
}

export function GetAITaggingStatusSummary() {
  return window['go']['main']['App']['GetAITaggingStatusSummary']();
}

export function GetAllDirectories() {
  return window['go']['main']['App']['GetAllDirectories']();
}

export function GetAllTags() {
  return window['go']['main']['App']['GetAllTags']();
}

export function GetAllVideos() {
  return window['go']['main']['App']['GetAllVideos']();
}

export function GetCleanupCandidates(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetCleanupCandidates'](arg1, arg2, arg3);
}

export function GetCleanupStatus() {
  return window['go']['main']['App']['GetCleanupStatus']();
}

export function GetLocalMLRuntimeStatus() {
  return window['go']['main']['App']['GetLocalMLRuntimeStatus']();
}

export function GetPreviewSession(arg1) {
  return window['go']['main']['App']['GetPreviewSession'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetShortFeedServerStatus() {
  return window['go']['main']['App']['GetShortFeedServerStatus']();
}

export function GetStartupError() {
  return window['go']['main']['App']['GetStartupError']();
}

export function GetSubtitleEngineStatuses() {
  return window['go']['main']['App']['GetSubtitleEngineStatuses']();
}

export function GetSubtitleSegments(arg1) {
  return window['go']['main']['App']['GetSubtitleSegments'](arg1);
}

export function GetVideosByDirectory(arg1) {
  return window['go']['main']['App']['GetVideosByDirectory'](arg1);
}

export function GetVideosPaginated(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetVideosPaginated'](arg1, arg2, arg3, arg4);
}

export function IndexAIEmbeddings(arg1) {
  return window['go']['main']['App']['IndexAIEmbeddings'](arg1);
}

export function IndexLocalMLEmbeddings(arg1) {
  return window['go']['main']['App']['IndexLocalMLEmbeddings'](arg1);
}

export function ListAITagCandidates(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListAITagCandidates'](arg1, arg2, arg3);
}

export function LogFrontend(arg1, arg2, arg3) {
  return window['go']['main']['App']['LogFrontend'](arg1, arg2, arg3);
}

export function OpenDirectory(arg1) {
  return window['go']['main']['App']['OpenDirectory'](arg1);
}

export function PlayRandomVideo() {
  return window['go']['main']['App']['PlayRandomVideo']();
}

export function PlayVideo(arg1) {
  return window['go']['main']['App']['PlayVideo'](arg1);
}

export function PrepareSubtitleEngine(arg1) {
  return window['go']['main']['App']['PrepareSubtitleEngine'](arg1);
}

export function PreviewExternally(arg1) {
  return window['go']['main']['App']['PreviewExternally'](arg1);
}

export function RefreshLocalMLRuntimeStatus() {
  return window['go']['main']['App']['RefreshLocalMLRuntimeStatus']();
}

export function RefreshVideoMetadata(arg1) {
  return window['go']['main']['App']['RefreshVideoMetadata'](arg1);
}

export function RejectAITagCandidate(arg1) {
  return window['go']['main']['App']['RejectAITagCandidate'](arg1);
}

export function RejectAITagCandidatesByVideo(arg1) {
  return window['go']['main']['App']['RejectAITagCandidatesByVideo'](arg1);
}

export function RelocateVideo(arg1, arg2) {
  return window['go']['main']['App']['RelocateVideo'](arg1, arg2);
}

export function RemoveTagFromVideo(arg1, arg2) {
  return window['go']['main']['App']['RemoveTagFromVideo'](arg1, arg2);
}

export function RenameVideo(arg1, arg2) {
  return window['go']['main']['App']['RenameVideo'](arg1, arg2);
}

export function RetryAITagging(arg1) {
  return window['go']['main']['App']['RetryAITagging'](arg1);
}

export function ScanDirectory(arg1) {
  return window['go']['main']['App']['ScanDirectory'](arg1);
}

export function ScanDirectoryWithInfo(arg1) {
  return window['go']['main']['App']['ScanDirectoryWithInfo'](arg1);
}

export function SearchSubtitleMatches(arg1, arg2) {
  return window['go']['main']['App']['SearchSubtitleMatches'](arg1, arg2);
}

export function SearchVideos(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SearchVideos'](arg1, arg2, arg3, arg4, arg5);
}

export function SearchVideosByTags(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SearchVideosByTags'](arg1, arg2, arg3, arg4, arg5);
}

export function SearchVideosSmart(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['main']['App']['SearchVideosSmart'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}

export function SearchVideosWithFilters(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['main']['App']['SearchVideosWithFilters'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function StartCleanupAnalysis(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartCleanupAnalysis'](arg1, arg2, arg3);
}

export function SyncScanDirectories() {
  return window['go']['main']['App']['SyncScanDirectories']();
}

export function UpdateDirectory(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateDirectory'](arg1, arg2, arg3);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function UpdateTag(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateTag'](arg1, arg2, arg3);
}
