// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddDirectory(arg1:string,arg2:string):Promise<models.ScanDirectory>;

export function AddTagToVideo(arg1:number,arg2:number):Promise<void>;

export function AddVideo(arg1:string):Promise<models.Video>;

export function CreateTag(arg1:string,arg2:string):Promise<models.Tag>;

export function DeleteDirectory(arg1:number):Promise<void>;

export function DeleteTag(arg1:number):Promise<void>;

export function DeleteVideo(arg1:number,arg2:boolean):Promise<void>;

export function GetAllDirectories():Promise<Array<models.ScanDirectory>>;

export function GetAllTags():Promise<Array<models.Tag>>;

export function GetAllVideos():Promise<Array<models.Video>>;

export function GetSettings():Promise<models.Settings>;

export function GetVideosByDirectory(arg1:string):Promise<Array<models.Video>>;

export function GetVideosPaginated(arg1:number,arg2:number,arg3:number,arg4:number):Promise<Array<models.Video>>;

export function OpenDirectory(arg1:number):Promise<void>;

export function PlayRandomVideo():Promise<models.Video>;

export function PlayVideo(arg1:number):Promise<void>;

export function RemoveTagFromVideo(arg1:number,arg2:number):Promise<void>;

export function ScanDirectory(arg1:string):Promise<Array<string>>;

export function SearchVideos(arg1:string,arg2:number,arg3:number,arg4:number,arg5:number):Promise<Array<models.Video>>;

export function SearchVideosByTags(arg1:Array<number>,arg2:number,arg3:number,arg4:number,arg5:number):Promise<Array<models.Video>>;

export function SearchVideosWithFilters(arg1:string,arg2:Array<number>,arg3:number,arg4:number,arg5:number,arg6:number):Promise<Array<models.Video>>;

export function SelectDirectory():Promise<string>;

export function UpdateDirectory(arg1:number,arg2:string,arg3:string):Promise<void>;

export function UpdateSettings(arg1:boolean,arg2:boolean,arg3:string,arg4:number,arg5:boolean,arg6:boolean):Promise<void>;

export function UpdateTag(arg1:number,arg2:string,arg3:string):Promise<void>;
