// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDirectory(arg1, arg2) {
  return window['go']['main']['App']['AddDirectory'](arg1, arg2);
}

export function AddTagToVideo(arg1, arg2) {
  return window['go']['main']['App']['AddTagToVideo'](arg1, arg2);
}

export function AddVideo(arg1) {
  return window['go']['main']['App']['AddVideo'](arg1);
}

export function CheckSubtitleDependencies() {
  return window['go']['main']['App']['CheckSubtitleDependencies']();
}

export function CreateTag(arg1, arg2) {
  return window['go']['main']['App']['CreateTag'](arg1, arg2);
}

export function DeleteDirectory(arg1) {
  return window['go']['main']['App']['DeleteDirectory'](arg1);
}

export function DeleteTag(arg1) {
  return window['go']['main']['App']['DeleteTag'](arg1);
}

export function DeleteVideo(arg1, arg2) {
  return window['go']['main']['App']['DeleteVideo'](arg1, arg2);
}

export function DownloadSubtitleDependencies() {
  return window['go']['main']['App']['DownloadSubtitleDependencies']();
}

export function GenerateSubtitle(arg1) {
  return window['go']['main']['App']['GenerateSubtitle'](arg1);
}

export function GetAllDirectories() {
  return window['go']['main']['App']['GetAllDirectories']();
}

export function GetAllTags() {
  return window['go']['main']['App']['GetAllTags']();
}

export function GetAllVideos() {
  return window['go']['main']['App']['GetAllVideos']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetVideosByDirectory(arg1) {
  return window['go']['main']['App']['GetVideosByDirectory'](arg1);
}

export function GetVideosPaginated(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetVideosPaginated'](arg1, arg2, arg3, arg4);
}

export function OpenDirectory(arg1) {
  return window['go']['main']['App']['OpenDirectory'](arg1);
}

export function PlayRandomVideo() {
  return window['go']['main']['App']['PlayRandomVideo']();
}

export function PlayVideo(arg1) {
  return window['go']['main']['App']['PlayVideo'](arg1);
}

export function RemoveTagFromVideo(arg1, arg2) {
  return window['go']['main']['App']['RemoveTagFromVideo'](arg1, arg2);
}

export function ScanDirectory(arg1) {
  return window['go']['main']['App']['ScanDirectory'](arg1);
}

export function SearchVideos(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SearchVideos'](arg1, arg2, arg3, arg4, arg5);
}

export function SearchVideosByTags(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SearchVideosByTags'](arg1, arg2, arg3, arg4, arg5);
}

export function SearchVideosWithFilters(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SearchVideosWithFilters'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function UpdateDirectory(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateDirectory'](arg1, arg2, arg3);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function UpdateTag(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateTag'](arg1, arg2, arg3);
}
