// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {services} from '../models';
import {subtitleparser} from '../models';

export function AddDirectory(arg1:string,arg2:string):Promise<models.ScanDirectory>;

export function AddTagToVideo(arg1:number,arg2:number):Promise<void>;

export function AddVideo(arg1:string):Promise<models.Video>;

export function AnalyzeVideoFaces(arg1:number):Promise<services.VideoFaceAnalysisResult>;

export function ApproveAITagCandidate(arg1:number):Promise<services.AITaggingReviewItem>;

export function BatchAddTagToVideos(arg1:Array<number>,arg2:number):Promise<services.BatchVideoOperationResult>;

export function BatchDeleteVideos(arg1:Array<number>,arg2:boolean):Promise<services.BatchVideoOperationResult>;

export function BatchRefreshVideoMetadata(arg1:Array<number>):Promise<services.BatchVideoOperationResult>;

export function BatchRemoveTagFromVideos(arg1:Array<number>,arg2:number):Promise<services.BatchVideoOperationResult>;

export function CancelSubtitle():Promise<void>;

export function CheckSubtitleDependencies():Promise<Record<string, boolean>>;

export function CreateTag(arg1:string,arg2:string):Promise<models.Tag>;

export function DeleteDirectory(arg1:number):Promise<void>;

export function DeleteTag(arg1:number):Promise<void>;

export function DeleteVideo(arg1:number,arg2:boolean):Promise<void>;

export function DownloadSubtitleDependencies():Promise<void>;

export function ForceGenerateSubtitle(arg1:services.SubtitleGenerateRequest):Promise<services.SubtitleGenerateResult>;

export function GenerateSubtitle(arg1:services.SubtitleGenerateRequest):Promise<services.SubtitleGenerateResult>;

export function GetAITaggingStatusSummary():Promise<services.AITaggingStatusSummary>;

export function GetAllDirectories():Promise<Array<models.ScanDirectory>>;

export function GetAllTags():Promise<Array<models.Tag>>;

export function GetAllVideos():Promise<Array<models.Video>>;

export function GetCleanupCandidates(arg1:number,arg2:number,arg3:number):Promise<services.CleanupAnalysis>;

export function GetCleanupStatus():Promise<services.CleanupStatus>;

export function GetLocalMLRuntimeStatus():Promise<services.LocalMLRuntimeStatus>;

export function GetPreviewSession(arg1:number):Promise<services.PreviewSession>;

export function GetSettings():Promise<models.Settings>;

export function GetShortFeedServerStatus():Promise<services.ShortFeedServerStatus>;

export function GetStartupError():Promise<string>;

export function GetSubtitleEngineStatuses():Promise<Array<services.SubtitleEngineStatus>>;

export function GetSubtitleSegments(arg1:number):Promise<Array<subtitleparser.Segment>>;

export function GetVideosByDirectory(arg1:string):Promise<Array<models.Video>>;

export function GetVideosPaginated(arg1:number,arg2:number,arg3:number,arg4:number):Promise<Array<models.Video>>;

export function IndexAIEmbeddings(arg1:number):Promise<services.LocalMLEmbeddingIndexResult>;

export function IndexLocalMLEmbeddings(arg1:number):Promise<services.LocalMLEmbeddingIndexResult>;

export function ListAITagCandidates(arg1:number,arg2:string,arg3:string):Promise<Array<services.AITaggingReviewItem>>;

export function LogFrontend(arg1:string,arg2:string,arg3:string):Promise<void>;

export function OpenDirectory(arg1:number):Promise<void>;

export function PlayRandomVideo():Promise<services.PlaybackAttemptResult>;

export function PlayVideo(arg1:number):Promise<services.PlaybackAttemptResult>;

export function PrepareSubtitleEngine(arg1:services.SubtitleEngine):Promise<void>;

export function PreviewExternally(arg1:number):Promise<void>;

export function RefreshLocalMLRuntimeStatus():Promise<services.LocalMLRuntimeStatus>;

export function RefreshVideoMetadata(arg1:number):Promise<void>;

export function RejectAITagCandidate(arg1:number):Promise<void>;

export function RejectAITagCandidatesByVideo(arg1:number):Promise<number>;

export function RelocateVideo(arg1:number,arg2:string):Promise<void>;

export function RemoveTagFromVideo(arg1:number,arg2:number):Promise<void>;

export function RenameVideo(arg1:number,arg2:string):Promise<void>;

export function RetryAITagging(arg1:number):Promise<void>;

export function ScanDirectory(arg1:string):Promise<Array<string>>;

export function ScanDirectoryWithInfo(arg1:string):Promise<Array<services.ScannedFile>>;

export function SearchSubtitleMatches(arg1:string,arg2:number):Promise<Array<services.SubtitleSearchMatch>>;

export function SearchVideos(arg1:string,arg2:number,arg3:number,arg4:number,arg5:number):Promise<Array<models.Video>>;

export function SearchVideosByTags(arg1:Array<number>,arg2:number,arg3:number,arg4:number,arg5:number):Promise<Array<models.Video>>;

export function SearchVideosSmart(arg1:string,arg2:Array<number>,arg3:number,arg4:number,arg5:number,arg6:number,arg7:number,arg8:number,arg9:number,arg10:number):Promise<Array<models.Video>>;

export function SearchVideosWithFilters(arg1:string,arg2:Array<number>,arg3:number,arg4:number,arg5:number,arg6:number,arg7:number,arg8:number,arg9:number,arg10:number):Promise<Array<models.Video>>;

export function SelectDirectory():Promise<string>;

export function StartCleanupAnalysis(arg1:number,arg2:number,arg3:number):Promise<services.CleanupStatus>;

export function SyncScanDirectories():Promise<services.ScanSyncResult>;

export function UpdateDirectory(arg1:number,arg2:string,arg3:string):Promise<void>;

export function UpdateSettings(arg1:models.Settings):Promise<void>;

export function UpdateTag(arg1:number,arg2:string,arg3:string):Promise<void>;
